DROP TABLE IF EXISTS `urt`;
CREATE TABLE `urt` (
  
  `id` smallint(4) unsigned NOT NULL AUTO_INCREMENT,
  `id_user` smallint(4) unsigned ,
  `user` varchar(100) COLLATE utf8_general_ci ,
  `p1` tinyint(2) unsigned ,
  `p2_anios` tinyint(2) unsigned ,
  `p2_meses` tinyint(2) unsigned ,
  `p3_anios` tinyint(2) unsigned ,
  `p3_meses` tinyint(2) unsigned ,
  `p4` tinyint(2) unsigned ,
  `p5` tinyint(2) unsigned ,
  `p6` tinyint(2) unsigned ,
  `p7` tinyint(2) unsigned ,
  `p8_1` tinyint(2) unsigned ,
  `p8_2` tinyint(2) unsigned ,
  `p8_3` tinyint(2) unsigned ,
  `p8_4` tinyint(2) unsigned ,
  `p8_5` tinyint(2) unsigned ,
  `p8_6` tinyint(2) unsigned ,
  `p8_7` tinyint(2) unsigned ,
  `p8_8` tinyint(2) unsigned ,
  `p8_9` tinyint(2) unsigned ,
  `p8_10` tinyint(2) unsigned ,
  `p8_11` tinyint(2) unsigned ,
  `p9` tinyint(2) unsigned ,
  `p10` tinyint(2) unsigned ,
  `p11` tinyint(2) unsigned ,
  `p12` tinyint(2) unsigned ,
  `p13_1` tinyint(2) unsigned ,
  `p13_2` tinyint(2) unsigned ,
  `p13_3` tinyint(2) unsigned ,
  `p13_4` tinyint(2) unsigned ,
  `p13_5` tinyint(2) unsigned ,
  `p13_6` tinyint(2) unsigned ,
  `p13_7` tinyint(2) unsigned ,
  `p13_8` tinyint(2) unsigned ,
  `p13_otrocual` text,
  `p14` tinyint(2) unsigned ,
  `p15_1` tinyint(2) unsigned ,
  `p15_2` tinyint(2) unsigned ,
  `p15_3` tinyint(2) unsigned ,
  `p15_4` tinyint(2) unsigned ,
  `p15_5` tinyint(2) unsigned ,
  `p15_6` tinyint(2) unsigned ,
  `p15_7` tinyint(2) unsigned ,
  `p15_8` tinyint(2) unsigned ,
  `p15_otrocual` text,
  `p16` tinyint(2) unsigned ,
  `p17` tinyint(2) unsigned ,
  `p18` tinyint(2) unsigned ,
  `p19_a` tinyint(2) unsigned ,
  `p19_b` tinyint(2) unsigned ,
  `p19_c` tinyint(2) unsigned ,
  `p20_a` tinyint(2) unsigned ,
  `p20_b` tinyint(2) unsigned ,
  `p20_c` tinyint(2) unsigned ,
  `p20_d` tinyint(2) unsigned ,
  `p20_e` tinyint(2) unsigned ,
  `p21_a` tinyint(2) unsigned ,
  `p21_b` tinyint(2) unsigned ,
  `p21_c` tinyint(2) unsigned ,
  `p21_d` tinyint(2) unsigned ,
  `p21_e` tinyint(2) unsigned ,
  `p21_f` tinyint(2) unsigned ,
  `p22` tinyint(2) unsigned ,
  `p23` tinyint(2) unsigned ,
  `p24_1` tinyint(2) unsigned ,
  `p24_2` tinyint(2) unsigned ,
  `p24_3` tinyint(2) unsigned ,
  `p24_4` tinyint(2) unsigned ,
  `p24_5` tinyint(2) unsigned ,
  `p24_6` tinyint(2) unsigned ,
  `p24_7` tinyint(2) unsigned ,
  `p24_8` tinyint(2) unsigned ,
  `p24_9` tinyint(2) unsigned ,
  `p24_10` tinyint(2) unsigned ,
  `p24_11` tinyint(2) unsigned ,
  `p24_12` tinyint(2) unsigned ,
  `p24_13` tinyint(2) unsigned ,
  `p24_otrocual` text,
  `p25_a` tinyint(2) unsigned ,
  `p25_b` tinyint(2) unsigned ,
  `p26_a` tinyint(2) unsigned ,
  `p26_b` tinyint(2) unsigned ,
  `p27` tinyint(2) unsigned ,
  `p28` tinyint(2) unsigned ,
  `p29` tinyint(2) unsigned ,
  `p30` tinyint(2) unsigned ,
  `p31` tinyint(2) unsigned ,
  `p32_1` tinyint(2) unsigned ,
  `p32_2` tinyint(2) unsigned ,
  `p32_3` tinyint(2) unsigned ,
  `p32_4` tinyint(2) unsigned ,
  `p32_5` tinyint(2) unsigned ,
  `p32_6` tinyint(2) unsigned ,
  `p32_7` tinyint(2) unsigned ,
  `p32_8` tinyint(2) unsigned ,
  `p32_9` tinyint(2) unsigned ,
  `p32_otrocual` text,
  `p33_1` tinyint(2) unsigned ,
  `p33_2` tinyint(2) unsigned ,
  `p33_3` tinyint(2) unsigned ,
  `p33_4` tinyint(2) unsigned ,
  `p33_5` tinyint(2) unsigned ,
  `p33_6` tinyint(2) unsigned ,
  `p33_7` tinyint(2) unsigned ,
  `p33_8` tinyint(2) unsigned ,
  `p33_9` tinyint(2) unsigned ,
  `p33_otrocual` text,
  `p34_a` tinyint(2) unsigned ,
  `p34_b` tinyint(2) unsigned ,
  `p34_c` tinyint(2) unsigned ,
  `p34_d` tinyint(2) unsigned ,
  `p34_e` tinyint(2) unsigned ,
  `p35` tinyint(2) unsigned ,
  `p35_otrocual` text,
  `p36_a` tinyint(2) unsigned ,
  `p36_b` tinyint(2) unsigned ,
  `p36_c` tinyint(2) unsigned ,
  `p36_d` tinyint(2) unsigned ,
  `p36_e` tinyint(2) unsigned ,
  `p37_nivel` tinyint(2) unsigned ,
  `p37_estructura` tinyint(2) unsigned ,
  `p37_sede` varchar(100) COLLATE utf8_general_ci ,
  `p38` tinyint(2) unsigned ,
  `p39` tinyint(2) unsigned ,

  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;